AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ServerName:
    Type: String
    Description: Name of server

Resources:
  Monitor:
    Type: "EQ::MONITOR::NAGIOS"
    Properties:
      Name: !Ref ServerName

Outputs:
  InstanceId:
    Value: !GetAtt Monitor.Id
